version: '3.5'
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    entrypoint: 
      - /bin/sh
      - -c 
      - sudo apt update && sudo apt install iproute2 -y && ip -4 route list match 0/0 | awk '{print $$3"    host.docker.internal"}' | sudo tee -a /etc/hosts && echo "51.11.46.27   $PBHOSTURL" | sudo tee -a /etc/hosts && /opt/bin/entry_point.sh 
    healthcheck:
      test: ["CMD", "curl", "-f", "https://$PBHOSTURL"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s